
import { getConnection } from "../config/db.js";

async function runSchemaUpdate() {
    let conn;
    try {
        console.log("Starting schema update...");
        conn = await getConnection();

        // 1. ADD TOKENS TO STUDENTS (USERS TABLE? OR STUDENTS TABLE?)
        // Assuming STUDENTS and COMPANIES tables exist, or just USERS?
        // Let's check dbService from before. It seems there is STUDENTS table.
        // We will try adding columns. If they exist, Oracle throws ORA-01430. We catch and ignore.

        try {
            await conn.execute(`ALTER TABLE STUDENTS ADD (TOKENS_REMAINING NUMBER DEFAULT 5, MAX_TOKENS NUMBER DEFAULT 5)`);
            console.log("Added TOKENS columns to STUDENTS.");
        } catch (e) {
            if (e.message.includes("ORA-01430")) console.log("TOKENS columns already exist.");
            else console.error("Error adding TOKENS:", e.message);
        }

        // 2. ADD QUOTA TO JOBS
        try {
            await conn.execute(`ALTER TABLE JOBS ADD (INTERVIEW_QUOTA NUMBER DEFAULT 10, ACCEPTED_COUNT NUMBER DEFAULT 0, IS_ACTIVE NUMBER(1) DEFAULT 1)`);
            console.log("Added QUOTA columns to JOBS.");
        } catch (e) {
            if (e.message.includes("ORA-01430")) console.log("QUOTA columns already exist.");
            else console.error("Error adding QUOTA:", e.message);
        }

        // 3. CREATE ROOMS TABLE
        try {
            await conn.execute(`
                CREATE TABLE ROOMS (
                    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    NAME VARCHAR2(50) NOT NULL UNIQUE
                )
            `);
            console.log("Created ROOMS table.");

            // Seed Rooms
            await conn.execute(`INSERT INTO ROOMS (NAME) VALUES ('Salle A1')`);
            await conn.execute(`INSERT INTO ROOMS (NAME) VALUES ('Salle A2')`);
            await conn.execute(`INSERT INTO ROOMS (NAME) VALUES ('Salle B1')`);
            await conn.execute(`INSERT INTO ROOMS (NAME) VALUES ('Salle B2')`);
            console.log("Seeded ROOMS.");

        } catch (e) {
            if (e.message.includes("ORA-00955")) console.log("ROOMS table already exists.");
            else console.error("Error creating ROOMS:", e.message);
        }

        // 4. ENSURE INTERVIEWS HAS ROOM_ID AND START_TIME/END_TIME
        // Based on previous reads, INTERVIEWS has ID, DATE_TIME...
        // We need ROOM_ID.
        try {
            await conn.execute(`ALTER TABLE INTERVIEWS ADD (ROOM_ID NUMBER, DURATION NUMBER DEFAULT 20)`);
            // FK constraint?
            // await conn.execute(`ALTER TABLE INTERVIEWS ADD CONSTRAINT FK_INTERVIEWS_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID)`);
            console.log("Added ROOM_ID to INTERVIEWS.");
        } catch (e) {
            if (e.message.includes("ORA-01430")) console.log("ROOM_ID column already exists.");
            else console.error("Error adding ROOM_ID:", e.message);
        }

        await conn.commit();
        console.log("Schema update completed.");
    } catch (err) {
        console.error("Schema update failed", err);
    } finally {
        if (conn) {
            try { await conn.close(); } catch (e) { console.error(e); }
        }
    }
}

runSchemaUpdate();
